version: '3.8'

services:
  cats:
    build: ./
    command: ./wait-for-postgres.sh db ./app
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=220095Qwe

  db:
    restart: always
    image: postgres:latest
#    volumes:
#      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5436"
    environment:
      - POSTGRES_PASSWORD=220095Qwe
