port: ":8000"

db:
  pos: "postgres"
  username: "user"
# ПОМЕНЯТЬ ХОСТ НА "postgres" при билдинге
  host: "localhost"
  port: "5432"
  dbase: "postgres"

mongodb:
  username: "root"
  port: "27017"
  dbase: "mongodb"
  collection: "mongocl"

redis:
  host: "localhost"
  port: "6379"
