port: ":8000"


db:
  pos: "postgres"
  username: "user"
  host: "postgres"
  port: "5432"
  dbase: "postgres"


mongodb:
#  username: "mongodb"
#  password: "mongodb"
  host: "localhost"
  port: "27017"
  dbase: "mongo"
  collection: "mongo"

