port: ":8000"


db:
  pos: "postgres"
  username: "user"
  host: "postgres"
  port: "5432"
  dbase: "postgres"


mongodb:
  username: "root"
  port: "27017"
  dbase: "mongodb"
  collection: "mongocl"

